### ISSUE TITLE
System read wrong

### ISSUE THREAD

**Issue by tragicdog** [dumbo25/conky-for-mac#1]
I have a mid 2012 MacBook pro and it showing up as a mid-2009 MacBook pro in your widget. 
<img width="479" alt="screen shot 2017-06-06 at 8 59 37 am" src="https://user-images.githubusercontent.com/322642/26838985-997ef582-4a96-11e7-8017-166d5e6f9760.png">
<img width="246" alt="screen shot 2017-06-06 at 8 59 28 am" src="https://user-images.githubusercontent.com/322642/26838986-997f78cc-4a96-11e7-878c-38c5579a3afe.png">

I didn't change anything in the widget just put it in the folder.

**Comment by dumbo25** [comment]
I updated mac-for-conky and added command to pull Mac Model. I just had Model hardcoded.

A bunch of the data in the image is off (e.g., Used: shows "wired)", and Public IP: shows "PhysMem").

If you could run the command from echo $(...) in a terminal window and send me the output plus a new screen shot with the newly checked-in code I'll see if I can figure out what is wrong.

Thanks.
Jeff

**Comment by dumbo25** [comment]
I also updated Processor instead of hardcoding.
